### ISSUE TITLE
Multiple replace in one call.

### ISSUE THREAD

**Issue by bxyhxyh** [zzzprojects/findandreplace#11]
It seems I can't replace multiple texts in one call.
For example when I have to replace 7 texts with another 7 texts, I have to call fnr.exe 7 times.
It could be done adding expressions find1, find2, find3, find4... find99 and replace1, replace2, replace3, replace4... replace99.
find1 and replace1 can be added without removing --find --replace for backward compatibility, like this.
```
fnr --cl --find1 "texttofind1" --replace1 "texttoreplace1" --find2 "texttofind2" --replace "texttoreplace2"
fnr --cl --find "texttofind1" --replace "texttoreplace1" --find2 "texttofind2" --replace "texttoreplace2"
```

**Comment by JonathanMagnan** [comment]
Hello @bxyhxyh ,

Thank you for your suggestion.

We will look at it to check if we could implemented something like this or not.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @bxyhxyh ,

We investigated this issue this Friday. Due to time limitation and how the library has been coded, we currently prefer to don't support this option yet.

However, we recommend you to create a bat file, it could make it easier to support multiple finds and replace instead to type each one.

Best Regards,

Jonathan

**Comment by bxyhxyh** [comment]
Thanks for the reply,
I was using a bat file when I'm writing this issue.
Then that "wrong console behavior" happened. Console windows appeared 7 times for that and that was very annoying. 
I've checked it on new 1.7.3 version on my bat file and that windows problem has fixed for my batch file.
