### ISSUE TITLE
Error when running as a scheduled task

### ISSUE THREAD

**Issue by kwork99** [zzzprojects/findandreplace#13]
I receive the following error when running the cli in version 1.7.4 as a scheduled task from a batch file on a Windows 2012 R2 Standard server.

Unhandled Exception: System.UnauthorizedAccessException: Access to the registry key 'Global' is denied.
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.InternalGetValue(String name, Object defaultValue, Boolean doNotExpand, Boolean checkSecurity)
   at Microsoft.Win32.RegistryKey.GetValue(String name)
   at System.Diagnostics.PerformanceMonitor.GetData(String item)
   at System.Diagnostics.PerformanceCounterLib.GetPerformanceData(String item)
   at System.Diagnostics.PerformanceCounterLib.get_CategoryTable()
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String category, String counter, Boolean& categoryExists)
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String machine, String category, String counter)
   at System.Diagnostics.PerformanceCounter.InitializeImpl()
   at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName, Boolean readOnly)
   at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName)
   at FindAndReplace.App.ProcessExtensions.FindIndexedProcessName(Int32 pid)
   at FindAndReplace.App.ProcessExtensions.Parent(Process process)
   at FindAndReplace.App.Program.Main(String[] args)

One of the commands I'm running that receives the error:
fnr.exe --cl --dir "%cd%" --fileMask "file.txt" --silent --showEncoding --excludeFileMask "*.dll, *.exe,*.bat" --useRegEx --find "\0" --replace ""

The user is a local user, non-admin. 

The command works when running as the user outside a scheduled task (which is puzzling). When running as a scheduled task (even with "Run with highest privileges" selected), it errors.

I was able to work around the issue by adding the user as a member of the local group "Performance Monitor Users" and restarting the server, but that isn't ideal for our environment. 

Thank you, this is a wonderful program and I'm glad to see it being actively worked on.

**Comment by JonathanMagnan** [comment]
Hello @kwork99 ,

Thank you for reporting, the tools should not write in RegistryKey to save his setting.

We will change the way it works.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @kwork99 ,

The v1.7.5 has been released.

The tools should no longer use `Registry Key` but a settings file instead.

Let me know if that's now working as expecting.

Best Regards,

Jonathan

**Comment by kwork99** [comment]
I'm out of the office but will retest and let you know as soon as I'm back.
Thank you!

**Comment by kwork99** [comment]
I'm still getting the error, but the version I just downloaded reports as 1.7.4, not 1.7.5.

**Comment by JonathanMagnan** [comment]
Thank @kwork99 for reporting,

For this one, it will be harder.

That happens because we try to append the text to the current console instead of opening a new console every time.

We can probably add an argument to open a new console every time instead (so skip the check).

Let me know if that solution could work for you.

Best Regards,

Jonathan

**Comment by kwork99** [comment]
Honestly, I don't know that I fully understand what you are describing with the console and why it is interacting with the PerformanceCounter.
I'm guessing it is related to issue #10 at https://github.com/zzzprojects/findandreplace/issues/10?

However, it's running as a scheduled task, so I won't see new consoles anyway, so if that's a way to make it work, sure. I am a little concerned if the goal is to run as a standard user why it needs to access those registry keys anyway?

**Comment by ghwanderer** [comment]
Hi kwork99 and Jonathan.

Since version 1.7.3 (the one first including the "wrong console behaviour" fix commit) up to current 1.7.7, I cannot run FnR from command line under Windows PE (GUI works in all versions however). I know most applications are not targetted to such environment, but command line in versions 1.7.0-1.7.2 run fine in Windows PE, so it has to be something first committed in 1.7.3.

I decided to test FnR 1.7.7 command line in a fresh, fully updated Win 7 x64 test VM and definitely something is wrong. The command "fnr --cl --help" doesn't throw an "unknown exception" like in Windows PE and finally works, but it takes to execute much longer than when running 1.7.2.

I monitored that simple command for registry/filesystem changes and was surprised by the creation of registry keys an values in the system\services branch!? I attach a picture. Why FnR 1.7.3+ needs to write to those? Even to the BITS service? I also registered an error event related to trying to open the Server service (?!) performance-something (I think is the same error kwork99 is experiencing). All this is not happening at all when running 1.7.0-1.7.2.
![fnr_177_reg_additions](https://user-images.githubusercontent.com/39070132/39730010-4f908a72-525f-11e8-8d0e-65c2715296a1.jpg)

**Comment by JonathanMagnan** [comment]
Hello @ghwanderer ,

Thank you for the additional information.

We will look at it and we will try to find another solution to handle console. I don't like what we are currently seeing either.

I will have one of my developers to look at it this week.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @kwork99 , @ghwanderer 

The v1.7.8 has been released.

We have made a rollback from change done in v1.7.3 about the console. It should now work as the version 1.7.2

Let me know if that is working as expected and work correctly in WindowsPE

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @kwork99 , @ghwanderer ,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
