### ISSUE TITLE
Suggestion: Store user.config in fnr.exe folder

### ISSUE THREAD

**Issue by ghwanderer** [zzzprojects/findandreplace#21]
Current path for user.config is not very convenient. And storing side-by-side with executable always help portability.

**Comment by JonathanMagnan** [comment]
Hello @ghwanderer ,

Thank you for your suggestion. Someone else reported us the same suggestion (https://github.com/zzzprojects/findandreplace/issues/14) but we are still not sure about the pertinence of this change.

Since there are only a few options to specify, we are still not convinced that this change is really needed. We may be wrong since we probably don't use this tools as much as you but we never had the portability problem. When I ask one of my developers to do something with this tools, it takes him a few seconds to specify options that are different from a request to another anyway.

What I currently like in this tools is there is only one executable, nothing more is required.

Best Regards,

Jonathan

**Comment by ghwanderer** [comment]
Sorry for bringing this back, I think I missed that closed issue. No problem at all Jonathan. The power of FnR is the command line mode (thank you for it!), and it's completely portable in that mode.

Then just let me suggest this: how about no user.config/registry fingerprint at all in GUI mode either?

**Comment by JonathanMagnan** [comment]
Hello @ghwanderer ,

This could be an option but staying with the old behavior is probably the easiest solution.

We might still consider in the future to create a button to generate a config file in the same directory as the `.exe`. So if some people want to make it easier to share setting,  they will be able.

However, that's not on our priority list for now.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Jon,

This issue will be closed since it has been answering.

We are still considering to provide this features in the future but for now, we believe we have higher priority task to complete.

Best Regards,

Jonathan
