### ISSUE TITLE
FNR don't run on Windows XP!!!

### ISSUE THREAD

**Issue by PiotrMP006** [zzzprojects/findandreplace#23]
The .NET Framework 4.0.3 (NOT 4.5!!!))is the latest supported .NET Framework version on Windows XP.

**Comment by JonathanMagnan** [comment]
Hello @PiotrMP006 ,

You are right, we currently release the product with the version .NET45.

We will try to downgrade the version. However, if we lose some features we will continue to support only .NET45 and you will need to use an oldest version since we have to plan to support 2 version in parallel. 

Best Regards,

Jonathan

**Comment by PiotrMP006** [comment]
When???!!!  Place....

**Comment by JonathanMagnan** [comment]
Hello @PiotrMP006 ,

Sorry for the delay.

The v1.7.9 has been released. We have downgraded the .NET Framework to 4.0 to support XP.

However, we cannot guarantee you that it will work.

If that doesn't work, you will need to download the source and built it on your side with Visual Studio on your window XP machine.

Let me know if that has worked.

Best Regards,

Jonathan
